[package]
name = "bdl-mobile-credentials"
version = "0.5.3"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"
links = "bdl-mobile-credentials"

[dependencies]
bdl-core = { path = "../bdl-core" }
bdl-tauri = { path = "../bdl-tauri" }
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", default-features = false }

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
