/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_33aca8ad76f08ca22a4db96dae16f4f3/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_33aca8ad76f08ca22a4db96dae16f4f3/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_33aca8ad76f08ca22a4db96dae16f4f3/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_33aca8ad76f08ca22a4db96dae16f4f3/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_33aca8ad76f08ca22a4db96dae16f4f3/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_33aca8ad76f08ca22a4db96dae16f4f3/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_33aca8ad76f08ca22a4db96dae16f4f3/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_33aca8ad76f08ca22a4db96dae16f4f3/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
  }
}
